/* Built-in album lists for Listening Log.
   This file is separate from index.html on purpose: Claude (or you) can update
   the app's logic in index.html without ever needing to touch or regenerate
   this file, and vice versa. Custom lists you add in-app, folders, renames,
   and listening progress are NOT stored here -- they live in your browser's
   local storage and persist automatically across updates to either file. */
const BUILTIN_LISTS = [
  {
    id: "100-albums-understand-music",
    title: "100 Albums to Understand Music",
    albums: [
      {a:"Miles Davis", t:"Kind of Blue", y:"1959", g:"Jazz"},
      {a:"The Beatles", t:"Revolver", y:"1966", g:"Rock / Pop"},
      {a:"Marvin Gaye", t:"What's Going On", y:"1971", g:"Soul"},
      {a:"Bob Dylan", t:"Highway 61 Revisited", y:"1965", g:"Folk Rock"},
      {a:"A Tribe Called Quest", t:"The Low End Theory", y:"1991", g:"Hip-Hop"},
      {a:"Joni Mitchell", t:"Blue", y:"1971", g:"Folk / Singer-Songwriter"},
      {a:"Kraftwerk", t:"Trans-Europe Express", y:"1977", g:"Electronic"},
      {a:"Aretha Franklin", t:"Lady Soul", y:"1968", g:"Soul"},
      {a:"The Velvet Underground & Nico", t:"The Velvet Underground & Nico", y:"1967", g:"Art Rock"},
      {a:"Fela Kuti", t:"Zombie", y:"1976", g:"Afrobeat"},
      {a:"Radiohead", t:"OK Computer", y:"1997", g:"Alternative Rock"},
      {a:"João Gilberto & Stan Getz", t:"Getz/Gilberto", y:"1964", g:"Bossa Nova"},
      {a:"Black Sabbath", t:"Paranoid", y:"1970", g:"Heavy Metal"},
      {a:"Lauryn Hill", t:"The Miseducation of Lauryn Hill", y:"1998", g:"Hip-Hop / R&B"},
      {a:"The Beach Boys", t:"Pet Sounds", y:"1966", g:"Pop / Rock"},
      {a:"Bob Marley & The Wailers", t:"Exodus", y:"1977", g:"Reggae"},
      {a:"Nina Simone", t:"I Put a Spell on You", y:"1965", g:"Jazz / Soul"},
      {a:"Daft Punk", t:"Discovery", y:"2001", g:"Electronic / Dance"},
      {a:"Johnny Cash", t:"At Folsom Prison", y:"1968", g:"Country"},
      {a:"Public Enemy", t:"It Takes a Nation of Millions to Hold Us Back", y:"1988", g:"Hip-Hop"},
      {a:"Jimi Hendrix Experience", t:"Are You Experienced", y:"1967", g:"Psychedelic Rock"},
      {a:"Björk", t:"Homogenic", y:"1997", g:"Art Pop / Electronic"},
      {a:"Stevie Wonder", t:"Innervisions", y:"1973", g:"Funk / Soul"},
      {a:"The Clash", t:"London Calling", y:"1979", g:"Punk / Rock"},
      {a:"Ali Farka Touré", t:"Savane", y:"2006", g:"African / Blues"},
      {a:"David Bowie", t:"The Rise and Fall of Ziggy Stardust and the Spiders from Mars", y:"1972", g:"Glam Rock"},
      {a:"Nas", t:"Illmatic", y:"1994", g:"Hip-Hop"},
      {a:"Billie Holiday", t:"Lady in Satin", y:"1958", g:"Jazz"},
      {a:"Talking Heads", t:"Remain in Light", y:"1980", g:"New Wave / Funk"},
      {a:"Dolly Parton", t:"Jolene", y:"1974", g:"Country"},
      {a:"Aphex Twin", t:"Selected Ambient Works 85–92", y:"1992", g:"Ambient / Electronic"},
      {a:"María Callas", t:"La Divina", y:"1950s", g:"Classical / Opera"},
      {a:"Wu-Tang Clan", t:"Enter the Wu-Tang (36 Chambers)", y:"1993", g:"Hip-Hop"},
      {a:"The Cure", t:"Disintegration", y:"1989", g:"Post-Punk / Gothic Rock"},
      {a:"Buena Vista Social Club", t:"Buena Vista Social Club", y:"1997", g:"Cuban / Latin"},
      {a:"Curtis Mayfield", t:"Super Fly", y:"1972", g:"Soul / Funk"},
      {a:"My Bloody Valentine", t:"Loveless", y:"1991", g:"Shoegaze"},
      {a:"John Coltrane", t:"A Love Supreme", y:"1965", g:"Jazz"},
      {a:"Missy Elliott", t:"Supa Dupa Fly", y:"1997", g:"Hip-Hop / R&B"},
      {a:"Pink Floyd", t:"The Dark Side of the Moon", y:"1973", g:"Progressive Rock"},
      {a:"King Tubby", t:"The Roots of Dub", y:"1975", g:"Dub"},
      {a:"Beyoncé", t:"Lemonade", y:"2016", g:"R&B / Pop"},
      {a:"Neil Young", t:"Harvest", y:"1972", g:"Americana"},
      {a:"N.W.A", t:"Straight Outta Compton", y:"1988", g:"Hip-Hop / Gangsta Rap"},
      {a:"Can", t:"Tago Mago", y:"1971", g:"Krautrock / Experimental"},
      {a:"Prince", t:"Purple Rain", y:"1984", g:"Funk / Pop / Rock"},
      {a:"Thelonious Monk", t:"Brilliant Corners", y:"1957", g:"Jazz"},
      {a:"Nirvana", t:"Nevermind", y:"1991", g:"Grunge"},
      {a:"Antônio Carlos Jobim", t:"Wave", y:"1967", g:"Bossa Nova"},
      {a:"Public Image Ltd.", t:"Metal Box", y:"1979", g:"Post-Punk"},
      {a:"Michael Jackson", t:"Thriller", y:"1982", g:"Pop / R&B"},
      {a:"Sly & the Family Stone", t:"There's a Riot Goin' On", y:"1971", g:"Funk / Soul"},
      {a:"Kate Bush", t:"Hounds of Love", y:"1985", g:"Art Pop"},
      {a:"The Wailers", t:"Catch a Fire", y:"1973", g:"Reggae"},
      {a:"Metallica", t:"Master of Puppets", y:"1986", g:"Metal"},
      {a:"Lee \"Scratch\" Perry", t:"Super Ape", y:"1976", g:"Dub"},
      {a:"Frank Ocean", t:"Blonde", y:"2016", g:"Alternative R&B"},
      {a:"Fleetwood Mac", t:"Rumours", y:"1977", g:"Pop Rock"},
      {a:"Aphex Twin", t:"Richard D. James Album", y:"1996", g:"IDM / Electronic"},
      {a:"The Stooges", t:"Raw Power", y:"1973", g:"Proto-Punk"},
      {a:"Kendrick Lamar", t:"To Pimp a Butterfly", y:"2015", g:"Hip-Hop / Jazz / Funk"},
      {a:"Ravi Shankar", t:"The Sounds of India", y:"1958", g:"Indian Classical"},
      {a:"OutKast", t:"Aquemini", y:"1998", g:"Southern Hip-Hop"},
      {a:"Kate Bush", t:"The Dreaming", y:"1982", g:"Experimental Pop"},
      {a:"Joy Division", t:"Unknown Pleasures", y:"1979", g:"Post-Punk"},
      {a:"Taylor Swift", t:"1989", y:"2014", g:"Pop"},
      {a:"Jimi Hendrix Experience", t:"Electric Ladyland", y:"1968", g:"Psychedelic Rock"},
      {a:"Dr. Dre", t:"The Chronic", y:"1992", g:"West Coast Hip-Hop"},
      {a:"Joni Mitchell", t:"The Hissing of Summer Lawns", y:"1975", g:"Jazz-Folk"},
      {a:"ABBA", t:"The Album", y:"1977", g:"Pop"},
      {a:"Burial", t:"Untrue", y:"2007", g:"UK Garage / Electronic"},
      {a:"Aretha Franklin", t:"Amazing Grace", y:"1972", g:"Gospel"},
      {a:"Sonic Youth", t:"Daydream Nation", y:"1988", g:"Alternative / Noise Rock"},
      {a:"Kanye West", t:"My Beautiful Dark Twisted Fantasy", y:"2010", g:"Hip-Hop"},
      {a:"Portishead", t:"Dummy", y:"1994", g:"Trip-Hop"},
      {a:"D'Angelo", t:"Voodoo", y:"2000", g:"Neo-Soul"},
      {a:"The Smiths", t:"The Queen Is Dead", y:"1986", g:"Indie / Jangle Pop"},
      {a:"Babatunde Olatunji", t:"Drums of Passion", y:"1960", g:"African / Percussion"},
      {a:"Beyoncé", t:"Renaissance", y:"2022", g:"Dance / R&B / House"},
      {a:"The Replacements", t:"Let It Be", y:"1984", g:"Alternative Rock"},
      {a:"Duke Ellington & John Coltrane", t:"Duke Ellington & John Coltrane", y:"1963", g:"Jazz"},
      {a:"Charli xcx", t:"BRAT", y:"2024", g:"Hyperpop / Dance Pop"},
      {a:"Gillian Welch", t:"Time (The Revelator)", y:"2001", g:"Americana"},
      {a:"Orchestra Baobab", t:"Pirates Choice", y:"1989", g:"Senegalese / Afro-Cuban"},
      {a:"The Chemical Brothers", t:"Dig Your Own Hole", y:"1997", g:"Big Beat / Electronic"},
      {a:"Lucinda Williams", t:"Car Wheels on a Gravel Road", y:"1998", g:"Americana / Country"},
      {a:"Tyler, the Creator", t:"IGOR", y:"2019", g:"Alternative R&B / Hip-Hop"},
      {a:"Talk Talk", t:"Spirit of Eden", y:"1988", g:"Art Rock / Ambient"},
      {a:"Nusrat Fateh Ali Khan", t:"Mustt Mustt", y:"1990", g:"Qawwali / World"},
      {a:"Sufjan Stevens", t:"Illinois", y:"2005", g:"Indie Folk / Chamber Pop"},
      {a:"Aphex Twin", t:"Selected Ambient Works Volume II", y:"1994", g:"Ambient"},
      {a:"Black Flag", t:"Damaged", y:"1981", g:"Hardcore Punk"},
      {a:"Radiohead", t:"In Rainbows", y:"2007", g:"Alternative / Art Rock"},
      {a:"Madonna", t:"Like a Prayer", y:"1989", g:"Pop"},
      {a:"Nick Drake", t:"Pink Moon", y:"1972", g:"Folk"},
      {a:"Serge Gainsbourg", t:"Histoire de Melody Nelson", y:"1971", g:"French Pop / Art Rock"},
      {a:"Ryuichi Sakamoto", t:"B-2 Unit", y:"1980", g:"Electronic / Experimental"},
      {a:"The Staple Singers", t:"Be Altitude: Respect Yourself", y:"1972", g:"Gospel / Soul"},
      {a:"Ibrahim Ferrer", t:"Buena Vista Social Club Presents Ibrahim Ferrer", y:"1999", g:"Cuban / Latin"},
      {a:"The Strokes", t:"Is This It", y:"2001", g:"Indie Rock"}
    ]
  },
  {
    id: "100-albums-2026-so-far",
    title: "100 Albums of 2026 — So Far",
    albums: [
      {a:"Gorillaz", t:"The Mountain", y:"2026", g:"Alternative / Art Pop"},
      {a:"Sunn O)))", t:"sunn O)))", y:"2026", g:"Drone Metal"},
      {a:"Olivia Rodrigo", t:"you seem pretty sad for a girl so in love", y:"2026", g:"Pop Rock"},
      {a:"Wendy Eisenberg", t:"Wendy Eisenberg", y:"2026", g:"Experimental Folk / Jazz"},
      {a:"Vince Staples", t:"Cry Baby", y:"2026", g:"Hip-Hop"},
      {a:"Robyn", t:"Sexistential", y:"2026", g:"Dance Pop"},
      {a:"Marisa Anderson", t:"The Anthology Of UnAmerican Folk Music", y:"2026", g:"Experimental Folk"},
      {a:"Kelela", t:"new avatar", y:"2026", g:"Alternative R&B"},
      {a:"The Black Crowes", t:"A Pound Of Feathers", y:"2026", g:"Southern Rock"},
      {a:"Underscores", t:"U", y:"2026", g:"Hyperpop / Alternative Pop"},
      {a:"Johnny Blue Skies & The Dark Clouds", t:"Mutiny After Midnight", y:"2026", g:"Country Rock"},
      {a:"Genesis Owusu", t:"REDSTAR WU & THE WORLDWIDE SCOURGE", y:"2026", g:"Alternative Hip-Hop"},
      {a:"Aldous Harding", t:"Train On The Island", y:"2026", g:"Art Folk"},
      {a:"Tyla", t:"A*POP", y:"2026", g:"Amapiano / Pop / R&B"},
      {a:"Neurosis", t:"An Undying Love For A Burning World", y:"2026", g:"Post-Metal"},
      {a:"RAYE", t:"THIS MUSIC MAY CONTAIN HOPE.", y:"2026", g:"Pop / Soul"},
      {a:"Jeff Parker ETA IVtet", t:"Happy Today", y:"2026", g:"Jazz / Experimental"},
      {a:"Charli xcx", t:"Wuthering Heights", y:"2026", g:"Art Pop / Alternative"},
      {a:"Lee \"Scratch\" Perry & Mouse On Mars", t:"Spatial, No Problem.", y:"2026", g:"Dub / Electronic"},
      {a:"Kacey Musgraves", t:"Middle Of Nowhere", y:"2026", g:"Country / Americana"},
      {a:"Iceage", t:"For Love Of Grace & The Hereafter", y:"2026", g:"Post-Punk"},
      {a:"Don Toliver", t:"OCTANE", y:"2026", g:"Hip-Hop / R&B"},
      {a:"BTS", t:"ARIRANG", y:"2026", g:"K-Pop"},
      {a:"Boards of Canada", t:"Inferno", y:"2026", g:"Ambient / Electronic"},
      {a:"My New Band Believe", t:"My New Band Believe", y:"2026", g:"Indie Rock / Experimental Pop"},
      {a:"YHWH Nailgun", t:"Magazine", y:"2026", g:"Art Punk / Experimental Rock"},
      {a:"Madonna", t:"CONFESSIONS II", y:"2026", g:"Dance Pop"},
      {a:"Tara Clerkin Trio", t:"Somewhere Good", y:"2026", g:"Experimental / Jazz"},
      {a:"Jack White", t:"Frozen Charlotte", y:"2026", g:"Rock"},
      {a:"Man/Woman/Chainsaw", t:"Cannonball", y:"2026", g:"Art Rock / Post-Punk"},
      {a:"Paul McCartney", t:"The Boys Of Dungeon Lane", y:"2026", g:"Rock / Pop"},
      {a:"skaiwater", t:"wonderful", y:"2026", g:"Experimental Hip-Hop"},
      {a:"Beth Orton", t:"The Ground Above", y:"2026", g:"Folk / Art Pop"},
      {a:"Isaiah Rashad", t:"It's Been Awful", y:"2026", g:"Southern Hip-Hop"},
      {a:"Shabaka", t:"Of The Earth", y:"2026", g:"Jazz / Experimental"},
      {a:"Kneecap", t:"FENIAN", y:"2026", g:"Irish Hip-Hop"},
      {a:"Kelsey Lu", t:"So Help Me God", y:"2026", g:"Art Pop / R&B"},
      {a:"Seefeel", t:"Sol.Hz", y:"2026", g:"Shoegaze / Electronic"},
      {a:"Kim Gordon", t:"PLAY ME", y:"2026", g:"Experimental Rock / Electronic"},
      {a:"Jalen Ngonda", t:"Doctrine Of Love", y:"2026", g:"Soul / R&B"},
      {a:"Angine de Poitrine", t:"Vol.II", y:"2026", g:"Experimental Rock"},
      {a:"Mitski", t:"Nothing's About To Happen To Me", y:"2026", g:"Indie Rock / Art Pop"},
      {a:"Heavenly", t:"Highway To Heavenly", y:"2026", g:"Indie Pop"},
      {a:"Jill Scott", t:"To Whom This May Concern", y:"2026", g:"R&B / Soul"},
      {a:"Lip Critic", t:"Theft World", y:"2026", g:"Electro-Punk"},
      {a:"The Twilight Sad", t:"IT'S THE LONG GOODBYE", y:"2026", g:"Post-Rock / Indie"},
      {a:"Beverly Glenn-Copeland", t:"Laughter In Summer", y:"2026", g:"Experimental Folk / Electronic"},
      {a:"Squeeze", t:"Trixies", y:"2026", g:"Pop Rock"},
      {a:"Altın Gün", t:"Garip", y:"2026", g:"Turkish Psychedelic / Folk"},
      {a:"The Lemon Twigs", t:"Look For Your Mind!", y:"2026", g:"Power Pop / Indie Rock"},
      {a:"Converge", t:"Love Is Not Enough", y:"2026", g:"Metalcore"},
      {a:"Hen Ogledd", t:"DISCOMBOBULATED", y:"2026", g:"Experimental / Avant-Pop"},
      {a:"The New Pornographers", t:"The Former Site Of", y:"2026", g:"Indie Rock / Power Pop"},
      {a:"Buck Meek", t:"The Mirror", y:"2026", g:"Indie Folk / Americana"},
      {a:"Julianna Barwick & Mary Lattimore", t:"Tragic Magic", y:"2026", g:"Ambient / Modern Classical"},
      {a:"Bill Orcutt & Mabe Fratti", t:"Almost Waking", y:"2026", g:"Experimental / Avant-Jazz"},
      {a:"Greg Mendez", t:"Beauty Land", y:"2026", g:"Indie Folk / Singer-Songwriter"},
      {a:"Bill Callahan", t:"My Days Of 58", y:"2026", g:"Americana / Singer-Songwriter"},
      {a:"They Might Be Giants", t:"The World Is To Dig", y:"2026", g:"Alternative Rock"},
      {a:"Tori Amos", t:"In Times Of Dragons", y:"2026", g:"Art Pop / Piano Rock"},
      {a:"Kehlani", t:"Kehlani", y:"2026", g:"R&B / Pop"},
      {a:"Bonnie \"Prince\" Billy", t:"We Are Together Again", y:"2026", g:"Folk / Americana"},
      {a:"Lucinda Williams", t:"World's Gone Wrong", y:"2026", g:"Americana / Country"},
      {a:"American Football", t:"American Football (LP4)", y:"2026", g:"Emo / Indie Rock"},
      {a:"Broken Social Scene", t:"Remember The Humans", y:"2026", g:"Indie Rock"},
      {a:"Kurt Vile", t:"Philadelphia's been good to me", y:"2026", g:"Indie Rock / Folk"},
      {a:"Avalon Emerson & The Charm", t:"Written Into Changes", y:"2026", g:"Electronic / Indie Pop"},
      {a:"The Soft Pink Truth", t:"Can Such Delightful Times Go On Forever?", y:"2026", g:"Experimental Electronic"},
      {a:"hemlocke springs", t:"the apple tree under the sea", y:"2026", g:"Alt-Pop / Hyperpop"},
      {a:"Thundercat", t:"Distracted", y:"2026", g:"Jazz-Funk / R&B"},
      {a:"Cardinals", t:"Masquerade", y:"2026", g:"Post-Rock / Indie"},
      {a:"Holly Humberstone", t:"Cruel World", y:"2026", g:"Pop / Alternative"},
      {a:"Courtney Barnett", t:"Creature Of Habit", y:"2026", g:"Indie Rock"},
      {a:"Courtney Marie Andrews", t:"Valentine", y:"2026", g:"Americana / Folk"},
      {a:"By Storm", t:"My Ghosts Go Ghost", y:"2026", g:"Experimental Hip-Hop"},
      {a:"Modern Woman", t:"Johnny's Dreamworld", y:"2026", g:"Art Rock"},
      {a:"Chanel Beads", t:"Your Day Will Come", y:"2026", g:"Dream Pop / Experimental"},
      {a:"Geologist", t:"Can I Get A Pack Of Camel Lights?", y:"2026", g:"Ambient / Experimental"},
      {a:"Nine Inch Nails & Boys Noize", t:"Nine Inch Noize", y:"2026", g:"Industrial / Electronic"},
      {a:"Horse Lords", t:"Demand To Be Taken To Heaven Alive!", y:"2026", g:"Experimental Rock / Math Rock"},
      {a:"Friko", t:"Something Worth Waiting For", y:"2026", g:"Indie Rock / Chamber Pop"},
      {a:"Yard Act", t:"You're Gonna Need A Little Music", y:"2026", g:"Post-Punk"},
      {a:"Nia Archives", t:"Emotional Junglist", y:"2026", g:"Jungle / Electronic"},
      {a:"Iron & Wine", t:"Hen's Teeth", y:"2026", g:"Indie Folk"},
      {a:"Joyce Manor", t:"I Used to Go To This Bar", y:"2026", g:"Punk / Indie Rock"},
      {a:"Melvins With Napalm Death", t:"Savage Imperial Death March", y:"2026", g:"Sludge / Grindcore"},
      {a:"Maria BC", t:"Marathon", y:"2026", g:"Ambient Folk"},
      {a:"Loraine James", t:"Detached From The Rest Of You", y:"2026", g:"Experimental Electronic"},
      {a:"Slift", t:"Fantasia", y:"2026", g:"Psychedelic Rock"},
      {a:"The Cribs", t:"Selling A Vibe", y:"2026", g:"Indie Rock"},
      {a:"Ora Cogan", t:"Hard Hearted Woman", y:"2026", g:"Dark Folk / Americana"},
      {a:"Graham Coxon", t:"Castle Park", y:"2026", g:"Alternative Rock"},
      {a:"Dry Cleaning", t:"Secret Love", y:"2026", g:"Post-Punk"},
      {a:"Ratboys", t:"Singin' To An Empty Chair", y:"2026", g:"Indie Rock / Alt-Country"},
      {a:"Mandy, Indiana", t:"URGH", y:"2026", g:"Noise Rock / Electronic"},
      {a:"A$AP Rocky", t:"Don't Be Dumb", y:"2026", g:"Hip-Hop"},
      {a:"Baby Keem", t:"Ca$ino", y:"2026", g:"Hip-Hop / Alternative"},
      {a:"Daphni", t:"Butterfly", y:"2026", g:"Electronic / Dance"}
    ]
  },
  {
    id: "music-list",
    title: "Music List",
    albums: [
      {a:"Phoebe Bridgers", t:"Stranger in the Alps", y:"2017", g:"Indie Folk / Singer-Songwriter"},
      {a:"Bright Eyes", t:"I'm Wide Awake, It's Morning", y:"2005", g:"Indie Folk / Americana"},
      {a:"Regina Spektor", t:"Far", y:"2009", g:"Indie Pop / Singer-Songwriter"},
      {a:"Mitski", t:"Bury Me at Makeout Creek", y:"2013", g:"Indie Rock"},
      {a:"Sufjan Stevens", t:"Carrie & Lowell", y:"2015", g:"Indie Folk"},
      {a:"The Front Bottoms", t:"The Front Bottoms", y:"2011", g:"Folk Punk / Indie Rock"},
      {a:"Adrianne Lenker", t:"songs", y:"2020", g:"Indie Folk"},
      {a:"Paul Simon", t:"Graceland", y:"1986", g:"Worldbeat / Pop Rock"},
      {a:"Chet Baker", t:"Chet Baker Sings", y:"1954", g:"Jazz / Vocal Jazz"},
      {a:"Ed Sheeran", t:"+", y:"2011", g:"Pop / Folk Pop"},
      {a:"Clairo", t:"Sling", y:"2021", g:"Indie Pop / Folk"},
      {a:"Anna Tivel", t:"The Question", y:"2017", g:"Indie Folk / Singer-Songwriter"},
      {a:"Bob Dylan", t:"Blood on the Tracks", y:"1975", g:"Folk Rock / Singer-Songwriter"},
      {a:"Ben Howard", t:"I Forget Where We Were", y:"2014", g:"Indie Folk / Alternative Rock"},
      {a:"Bon Iver", t:"For Emma, Forever Ago", y:"2007", g:"Indie Folk"},
      {a:"Black Country, New Road", t:"For the first time", y:"2021", g:"Art Rock / Post-Rock"},
      {a:"Joyce Manor", t:"Never Hungover Again", y:"2014", g:"Pop Punk / Indie Rock"},
      {a:"Taylor Swift", t:"Fearless (Taylor's Version)", y:"2021", g:"Country Pop / Pop"},
      {a:"Frankie Cosmos", t:"Next Thing", y:"2016", g:"Indie Pop"},
      {a:"Vance Joy", t:"Dream Your Life Away", y:"2014", g:"Indie Folk / Pop"},
      {a:"Elliott Smith", t:"Either/Or", y:"1997", g:"Indie Folk / Singer-Songwriter"},
      {a:"LANY", t:"LANY", y:"2017", g:"Dream Pop / Alternative Pop"},
      {a:"Joni Mitchell", t:"Blue", y:"1971", g:"Folk / Singer-Songwriter"},
      {a:"The Postal Service", t:"Give Up", y:"2003", g:"Indietronica / Synthpop"},
      {a:"Lucy Dacus", t:"Home Video", y:"2021", g:"Indie Rock / Singer-Songwriter"},
      {a:"Lorde", t:"Melodrama", y:"2017", g:"Art Pop / Electropop"},
      {a:"Better Oblivion Community Center", t:"Better Oblivion Community Center", y:"2019", g:"Indie Rock / Folk Rock"},
      {a:"Mac DeMarco", t:"Another One", y:"2015", g:"Indie Rock / Lo-Fi Pop"},
      {a:"Pinegrove", t:"Everything So Far", y:"2015", g:"Indie Rock / Emo"},
      {a:"Hot Mulligan", t:"You'll Be Fine", y:"2020", g:"Emo / Pop Punk"},
      {a:"Alex G", t:"RACE", y:"2010", g:"Lo-Fi Indie Rock"},
      {a:"Modern Baseball", t:"You're Gonna Miss It All", y:"2014", g:"Emo / Indie Rock"},
      {a:"Alvvays", t:"Antisocialites", y:"2017", g:"Indie Pop / Dream Pop"},
      {a:"Keaton Henson", t:"Birthdays", y:"2013", g:"Indie Folk / Singer-Songwriter"},
      {a:"Josh Garrels", t:"Love & War & The Sea In Between", y:"2011", g:"Indie Folk / Americana"},
      {a:"Vampire Weekend", t:"Modern Vampires of the City", y:"2013", g:"Indie Rock / Art Pop"},
      {a:"beabadoobee", t:"Beatopia", y:"2022", g:"Indie Rock / Dream Pop"},
      {a:"Damien Jurado", t:"The Horizon Just Laughed", y:"2018", g:"Indie Folk / Americana"},
      {a:"Death Cab for Cutie", t:"Transatlanticism", y:"2003", g:"Indie Rock / Emo"},
      {a:"Switchfoot", t:"Vice Verses", y:"2011", g:"Alternative Rock"},
      {a:"100 gecs", t:"1000 gecs", y:"2019", g:"Hyperpop / Experimental Pop"},
      {a:"Free Cake for Every Creature", t:"Talking Quietly of Anything With You", y:"2016", g:"Indie Folk / Lo-Fi Pop"},
      {a:"MJ Lenderman", t:"Boat Songs", y:"2022", g:"Indie Rock / Alt-Country"},
      {a:"Jeff Rosenstock", t:"We Cool?", y:"2015", g:"Punk Rock / Indie Rock"},
      {a:"boygenius", t:"The Record", y:"2023", g:"Indie Rock / Folk Rock"},
      {a:"Johnny Cash", t:"American IV: The Man Comes Around", y:"2002", g:"Country / Americana"},
      {a:"My Chemical Romance", t:"I Brought You My Bullets, You Brought Me Your Love", y:"2002", g:"Emo / Post-Hardcore"},
      {a:"Lucy Rose", t:"Like I Used To", y:"2012", g:"Indie Folk / Singer-Songwriter"},
      {a:"PinkPantheress", t:"To Hell with It", y:"2021", g:"UK Garage / Bedroom Pop"},
      {a:"Origami Angel", t:"Somewhere City", y:"2019", g:"Emo / Math Rock"},
      {a:"Indigo De Souza", t:"Any Shape You Take", y:"2021", g:"Indie Rock"},
      {a:"Damien Rice", t:"O", y:"2002", g:"Singer-Songwriter / Folk"},
      {a:"Turnstile", t:"GLOW ON", y:"2021", g:"Hardcore Punk / Alternative Rock"},
      {a:"Conor Oberst", t:"Upside Down Mountain", y:"2014", g:"Americana / Folk Rock"},
      {a:"Billy Joel", t:"The Stranger", y:"1977", g:"Pop Rock / Singer-Songwriter"},
      {a:"Cage the Elephant", t:"Melophobia", y:"2013", g:"Alternative Rock"},
      {a:"Blind Pilot", t:"3 Rounds and a Sound", y:"2008", g:"Indie Folk"},
      {a:"Wednesday", t:"I Was Trying to Describe You to Someone", y:"2020", g:"Indie Rock / Shoegaze"},
      {a:"JPEGMAFIA", t:"Veteran", y:"2018", g:"Experimental Hip-Hop"},
      {a:"Modest Mouse", t:"Good News for People Who Love Bad News", y:"2004", g:"Indie Rock"},
      {a:"Charli XCX", t:"BRAT", y:"2024", g:"Dance Pop / Electronic"},
      {a:"Sidney Gish", t:"No Dogs Allowed", y:"2017", g:"Indie Pop / Lo-Fi"},
      {a:"Jockstrap", t:"I Love You Jennifer B", y:"2022", g:"Art Pop / Electronic"},
      {a:"Big Thief", t:"Masterpiece", y:"2016", g:"Indie Rock / Folk Rock"},
      {a:"Nick Drake", t:"Pink Moon", y:"1972", g:"Folk / Singer-Songwriter"},
      {a:"SoKo", t:"I Thought I Was an Alien", y:"2012", g:"Indie Folk / Indie Pop"},
      {a:"Soccer Mommy", t:"Color Theory", y:"2020", g:"Indie Rock / Dream Pop"},
      {a:"Molchat Doma", t:"Этажи", y:"2018", g:"Post-Punk / Coldwave"},
      {a:"Earl Sweatshirt", t:"Some Rap Songs", y:"2018", g:"Experimental Hip-Hop"},
      {a:"James Blake", t:"The Colour in Anything", y:"2016", g:"Alternative R&B / Electronic"},
      {a:"brakence", t:"hypochondriac", y:"2022", g:"Hyperpop / Emo Rap"},
      {a:"Free Throw", t:"Those Days Are Gone", y:"2014", g:"Emo / Pop Punk"},
      {a:"Japanese Breakfast", t:"Jubilee", y:"2021", g:"Indie Pop / Art Pop"},
      {a:"Haley Heynderickx", t:"I Need to Start a Garden", y:"2018", g:"Indie Folk"},
      {a:"Snail Mail", t:"Valentine", y:"2021", g:"Indie Rock"},
      {a:"DOMi & JD BECK", t:"NOT TiGHT", y:"2022", g:"Jazz / Fusion"},
      {a:"Mark Kozelek", t:"Live at Phoenix Public House Melbourne", y:"2014", g:"Singer-Songwriter / Folk"},
      {a:"Lil Peep", t:"HELLBOY", y:"2016", g:"Emo Rap / Hip-Hop"},
      {a:"Marietta", t:"Summer Death", y:"2015", g:"Emo / Math Rock"},
      {a:"Fleetwood Mac", t:"Rumours", y:"1977", g:"Rock / Pop Rock"},
      {a:"Dijon", t:"Absolutely", y:"2021", g:"Alternative R&B / Soul"},
      {a:"The Smiths", t:"The Queen Is Dead", y:"1986", g:"Indie Rock / Jangle Pop"},
      {a:"Geese", t:"3D Country", y:"2023", g:"Indie Rock / Art Rock"},
      {a:"Olivia Rodrigo", t:"SOUR", y:"2021", g:"Pop Rock / Pop"},
      {a:"Perry Como", t:"And I Love You So", y:"1973", g:"Traditional Pop / Easy Listening"},
      {a:"Weyes Blood", t:"Titanic Rising", y:"2019", g:"Art Pop / Psychedelic Pop"},
      {a:"The Beatles", t:"Revolver", y:"1966", g:"Rock / Pop"},
      {a:"Drain", t:"California Cursed", y:"2020", g:"Hardcore Punk / Crossover Thrash"},
      {a:"King Krule", t:"6 Feet Beneath the Moon", y:"2013", g:"Alternative / Jazz Rock"},
      {a:"The Lumineers", t:"The Lumineers", y:"2012", g:"Folk Rock / Americana"},
      {a:"Quiet Light", t:"Fourth of July", y:"2023", g:"Alternative / Ambient Pop"},
      {a:"Laufey", t:"Everything I Know About Love", y:"2021", g:"Jazz Pop / Bedroom Pop"},
      {a:"Field Medic", t:"Songs from the Sunroom", y:"2017", g:"Indie Folk / Lo-Fi"},
      {a:"JPEGMAFIA & Danny Brown", t:"SCARING THE HOES", y:"2023", g:"Experimental Hip-Hop"},
      {a:"The Beths", t:"Expert in a Dying Field", y:"2022", g:"Indie Rock / Power Pop"},
      {a:"Band of Horses", t:"Cease to Begin", y:"2007", g:"Indie Rock / Americana"},
      {a:"Kate Bush", t:"Hounds of Love", y:"1985", g:"Art Pop / Art Rock"},
      {a:"Ben Folds", t:"Rockin' the Suburbs", y:"2001", g:"Piano Rock / Alternative"},
      {a:"Tyler, the Creator", t:"IGOR", y:"2019", g:"Alternative Hip-Hop / R&B"},
      {a:"Slaughter Beach, Dog", t:"Birdie", y:"2017", g:"Indie Folk / Indie Rock"},
      {a:"Lomelda", t:"Hannah", y:"2015", g:"Indie Folk / Lo-Fi"},
      {a:"Mount Eerie", t:"A Crow Looked at Me", y:"2017", g:"Experimental Folk / Singer-Songwriter"},
      {a:"Frank Ocean", t:"Blonde", y:"2016", g:"Alternative R&B"},
      {a:"Prince", t:"Purple Rain", y:"1984", g:"Pop / Funk / Rock"},
      {a:"Marty Robbins", t:"Gunfighter Ballads and Trail Songs", y:"1959", g:"Country / Western"},
      {a:"Cigarettes After Sex", t:"Cry", y:"2019", g:"Dream Pop / Slowcore"},
      {a:"Leith Ross", t:"To Learn", y:"2023", g:"Indie Folk / Singer-Songwriter"},
      {a:"The Weeknd", t:"Starboy", y:"2016", g:"Pop / R&B"},
      {a:"Feeble Little Horse", t:"Girl with Fish", y:"2023", g:"Noise Rock / Indie Rock"},
      {a:"Steve Lacy", t:"Gemini Rights", y:"2022", g:"Alternative R&B / Funk"},
      {a:"Samia", t:"The Baby", y:"2020", g:"Indie Rock / Singer-Songwriter"},
      {a:"The Microphones", t:"The Glow Pt. 2", y:"2001", g:"Experimental Folk / Lo-Fi"},
      {a:"Waylon Jennings & Willie Nelson", t:"Waylon & Willie", y:"1978", g:"Outlaw Country"},
      {a:"Bill Evans Trio", t:"Waltz for Debby", y:"1961", g:"Jazz / Piano Trio"},
      {a:"Tame Impala", t:"Currents", y:"2015", g:"Psychedelic Pop / Electronic Rock"},
      {a:"Birdy", t:"Fire Within", y:"2013", g:"Indie Pop / Singer-Songwriter"},
      {a:"Van Morrison", t:"Moondance", y:"1970", g:"Folk Rock / Soul"},
      {a:"Faye Webster", t:"Atlanta Millionaires Club", y:"2019", g:"Indie Folk / R&B"},
      {a:"Joanna Sternberg", t:"I've Got Me", y:"2023", g:"Indie Folk / Singer-Songwriter"},
      {a:"Daft Punk", t:"Discovery", y:"2001", g:"Electronic / French House"},
      {a:"Ethan Gruska", t:"En Garde", y:"2023", g:"Art Pop / Singer-Songwriter"},
      {a:"Injury Reserve", t:"By the Time I Get to Phoenix", y:"2021", g:"Experimental Hip-Hop"},
      {a:"Mirah", t:"You Think It's Like This But Really It's Like This", y:"2000", g:"Indie Folk / Experimental Pop"},
      {a:"The Beach Boys", t:"Pet Sounds", y:"1966", g:"Baroque Pop / Rock"},
      {a:"Bruno Mars, Anderson .Paak & Silk Sonic", t:"An Evening with Silk Sonic", y:"2021", g:"Soul / Funk / R&B"},
      {a:"Tigers Jaw", t:"Tigers Jaw", y:"2009", g:"Emo / Indie Rock"},
      {a:"Imagine Dragons", t:"Smoke + Mirrors", y:"2015", g:"Pop Rock / Alternative Rock"},
      {a:"Cocteau Twins", t:"Heaven or Las Vegas", y:"1990", g:"Dream Pop / Shoegaze"},
      {a:"The 1975", t:"The 1975", y:"2013", g:"Indie Pop / Alternative Rock"},
      {a:"Men I Trust", t:"Oncle Jazz", y:"2019", g:"Dream Pop / Indie Pop"},
      {a:"José González", t:"Veneer", y:"2003", g:"Indie Folk"},
      {a:"Julia Jacklin", t:"Crushing", y:"2019", g:"Indie Rock / Singer-Songwriter"},
      {a:"Dolly Parton", t:"Jolene", y:"1974", g:"Country"},
      {a:"Lil Yachty", t:"Let's Start Here.", y:"2023", g:"Psychedelic Rock / Alternative"},
      {a:"PUP", t:"Morbid Stuff", y:"2019", g:"Punk Rock / Indie Rock"},
      {a:"Nick Hakim", t:"Green Twins", y:"2017", g:"Alternative R&B / Soul"},
      {a:"MIKE", t:"Burning Desire", y:"2023", g:"Experimental Hip-Hop"},
      {a:"gnash", t:"u", y:"2017", g:"Pop / R&B"},
      {a:"Jon Foreman", t:"The Wonderlands: Darkness", y:"2015", g:"Singer-Songwriter / Folk"},
      {a:"Slowdive", t:"Souvlaki", y:"1993", g:"Shoegaze"},
      {a:"Everything But the Girl", t:"Amplified Heart", y:"1994", g:"Sophisti-Pop / Folk Pop"},
      {a:"Jon Bellion", t:"The Human Condition", y:"2016", g:"Pop / Hip-Hop"},
      {a:"Kevin Abstract", t:"ARIZONA baby", y:"2019", g:"Alternative Hip-Hop / R&B"},
      {a:"blackbear", t:"deadroses", y:"2015", g:"Alternative R&B / Pop"}
    ]
  },
  {
    id: "100-albums-deeper-picks",
    title: "100 Albums — Deeper Personalized Picks",
    albums: [
      {a:"Weatherday", t:"Come In", y:"2019", g:"Emo / Lo-Fi Indie Rock"},
      {a:"Chanel Beads", t:"Your Day Will Come", y:"2024", g:"Dream Pop / Experimental Pop"},
      {a:"Ovlov", t:"Am", y:"2013", g:"Indie Rock / Noise Pop"},
      {a:"Julie Byrne", t:"Not Even Happiness", y:"2017", g:"Indie Folk / Singer-Songwriter"},
      {a:"Palm", t:"Rock Island", y:"2018", g:"Experimental Rock / Math Rock"},
      {a:"Sadurn", t:"Radiator", y:"2022", g:"Indie Rock / Slowcore"},
      {a:"Nourished by Time", t:"Erotic Probiotic 2", y:"2023", g:"Alternative R&B / Art Pop"},
      {a:"Blue Bendy", t:"So Medieval", y:"2024", g:"Art Rock / Experimental Indie"},
      {a:"Sweet Trip", t:"Velocity: Design: Comfort", y:"2003", g:"Dream Pop / Electronic"},
      {a:"Horse Jumper of Love", t:"Natural Part", y:"2022", g:"Slowcore / Indie Rock"},
      {a:"Crying", t:"Beyond the Fleeting Gales", y:"2016", g:"Emo / Synthpop"},
      {a:"Florry", t:"The Holey Bible", y:"2024", g:"Alt-Country / Indie Rock"},
      {a:"Drowse", t:"Cold Air", y:"2017", g:"Slowcore / Dream Pop"},
      {a:"Model/Actriz", t:"Dogsbody", y:"2023", g:"Industrial / Post-Punk"},
      {a:"Joan Shelley", t:"Over and Even", y:"2015", g:"Indie Folk / Americana"},
      {a:"Weatherday", t:"Weatherglow", y:"2022", g:"Emo / Experimental"},
      {a:"Karate", t:"The Bed Is in the Ocean", y:"1998", g:"Indie Rock / Math Rock"},
      {a:"Chanel Beads", t:"Deep Down Happy", y:"2021", g:"Dream Pop / Experimental Pop"},
      {a:"Spencer Radcliffe & Everyone Else", t:"Enjoy the Great Outdoors", y:"2016", g:"Lo-Fi Indie"},
      {a:"Spirit of the Beehive", t:"Hypnic Jerks", y:"2018", g:"Experimental Rock / Dream Pop"},
      {a:"Ovlov", t:"TRU", y:"2013", g:"Indie Rock / Noise Pop"},
      {a:"Skullcrusher", t:"Quiet the Room", y:"2022", g:"Experimental Folk / Ambient"},
      {a:"Greg Freeman", t:"Burnover", y:"2024", g:"Indie Rock / Singer-Songwriter"},
      {a:"Palm", t:"Shadow Expert", y:"2017", g:"Experimental Rock / Math Rock"},
      {a:"Jessica Pratt", t:"On Your Own Love Again", y:"2015", g:"Psychedelic Folk"},
      {a:"Florist", t:"The Birds Outside Sang", y:"2016", g:"Indie Folk / Experimental"},
      {a:"Oso Oso", t:"The Yunahon Mixtape", y:"2014", g:"Emo / Indie Rock"},
      {a:"Runnner", t:"Always Repeating", y:"2021", g:"Indie Folk / Lo-Fi"},
      {a:"Sprain", t:"As Lost Through Collision", y:"2018", g:"Experimental Rock / Post-Rock"},
      {a:"Forth Wanderers", t:"Forth Wanderers", y:"2018", g:"Indie Rock / Emo"},
      {a:"Cryogeyser", t:"Cryogeyser", y:"2022", g:"Shoegaze / Indie Rock"},
      {a:"Andy Shauf", t:"The Party", y:"2016", g:"Indie Folk / Chamber Pop"},
      {a:"Hovvdy", t:"Cranberry", y:"2018", g:"Indie Folk / Lo-Fi Rock"},
      {a:"Sharp Pins", t:"Radio DDR", y:"2024", g:"Lo-Fi Indie Rock"},
      {a:"Knifeplay", t:"Pearlty", y:"2022", g:"Shoegaze / Indie Rock"},
      {a:"Everyone Asked About You", t:"Let's Be Enemies", y:"1999", g:"Indie Pop / Emo"},
      {a:"The Van Pelt", t:"Sultans of Sentiment", y:"1997", g:"Indie Rock / Emo"},
      {a:"Midwife", t:"Luminol", y:"2021", g:"Dream Pop / Slowcore"},
      {a:"Why?", t:"Alopecia", y:"2008", g:"Experimental Hip-Hop / Indie Rock"},
      {a:"Liv.e", t:"Couldn't Wait to Tell You...", y:"2020", g:"Alternative R&B / Neo-Soul"},
      {a:"Standing on the Corner", t:"Red Burns", y:"2017", g:"Experimental Hip-Hop / Ambient"},
      {a:"Mavi", t:"Let the Sun Talk", y:"2019", g:"Conscious Hip-Hop"},
      {a:"Pink Siifu", t:"GUMBO'!", y:"2019", g:"Experimental Hip-Hop"},
      {a:"Cities Aviv", t:"The Crashing Sound of How It Goes", y:"2014", g:"Experimental Hip-Hop"},
      {a:"Serengeti", t:"Kenny Dennis", y:"2012", g:"Alternative Hip-Hop"},
      {a:"Klein", t:"Lagata", y:"2016", g:"Experimental R&B / Electronic"},
      {a:"Backxwash", t:"I Lie Here Buried With My Rings and My Dresses", y:"2021", g:"Industrial Hip-Hop"},
      {a:"Slauson Malone 1", t:"Vergangenheitsbewältigung", y:"2020", g:"Experimental Hip-Hop / Ambient"},
      {a:"Fievel Is Glauque", t:"Flaming Swords", y:"2022", g:"Experimental Pop / Jazz"},
      {a:"Horse Lords", t:"The Common Task", y:"2020", g:"Experimental Rock / Math Rock"},
      {a:"Palm", t:"Trading Basics", y:"2015", g:"Experimental Rock"},
      {a:"Spirit of the Beehive", t:"ENTERTAINMENT, DEATH", y:"2021", g:"Experimental Rock / Dream Pop"},
      {a:"Guerilla Toss", t:"Famously Alive", y:"2022", g:"Art Punk / Dance Rock"},
      {a:"Sweeping Promises", t:"Hunger for a Way Out", y:"2020", g:"Post-Punk / Indie Pop"},
      {a:"Omni", t:"Deluxe", y:"2016", g:"Post-Punk / Art Rock"},
      {a:"Omni", t:"Networker", y:"2020", g:"Post-Punk / Indie Rock"},
      {a:"Cola", t:"Deep in View", y:"2022", g:"Post-Punk / Indie Rock"},
      {a:"Dummy", t:"Mandatory Enjoyment", y:"2021", g:"Krautrock / Dream Pop"},
      {a:"Julie Doiron", t:"Broken Girl", y:"1996", g:"Indie Folk / Slowcore"},
      {a:"Red House Painters", t:"Down Colorful Hill", y:"1992", g:"Slowcore / Indie Rock"},
      {a:"Codeine", t:"Frigid Stars LP", y:"1991", g:"Slowcore"},
      {a:"Low", t:"I Could Live in Hope", y:"1994", g:"Slowcore / Indie Rock"},
      {a:"Bedhead", t:"WhatFunLifeWas", y:"1994", g:"Slowcore / Indie Rock"},
      {a:"Idaho", t:"Year After Year", y:"1993", g:"Slowcore / Indie Rock"},
      {a:"Bluetile Lounge", t:"Lowercase", y:"1995", g:"Slowcore / Indie Rock"},
      {a:"Rex", t:"C", y:"1996", g:"Slowcore / Indie Rock"},
      {a:"The For Carnation", t:"The For Carnation", y:"1999", g:"Slowcore / Post-Rock"},
      {a:"Seam", t:"The Problem with Me", y:"1993", g:"Indie Rock / Slowcore"},
      {a:"Aldous Harding", t:"Party", y:"2017", g:"Art Folk / Indie"},
      {a:"Sibylle Baier", t:"Colour Green", y:"2006", g:"Indie Folk / Singer-Songwriter"},
      {a:"Linda Perhacs", t:"Parallelograms", y:"1970", g:"Psychedelic Folk"},
      {a:"Vashti Bunyan", t:"Just Another Diamond Day", y:"1970", g:"Psychedelic Folk"},
      {a:"Judee Sill", t:"Heart Food", y:"1973", g:"Baroque Folk / Singer-Songwriter"},
      {a:"Karen Dalton", t:"In My Own Time", y:"1971", g:"Folk / Blues"},
      {a:"Jackson C. Frank", t:"Jackson C. Frank", y:"1965", g:"Folk / Singer-Songwriter"},
      {a:"Bill Fay", t:"Countless Branches", y:"2020", g:"Folk / Singer-Songwriter"},
      {a:"Richard Buckner", t:"Devotion + Doubt", y:"1997", g:"Alt-Country / Indie Rock"},
      {a:"Smog", t:"Knock Knock", y:"1999", g:"Lo-Fi Folk / Indie Rock"},
      {a:"Broadcast", t:"The Noise Made by People", y:"2000", g:"Psychedelic Pop / Electronic"},
      {a:"The Books", t:"The Lemon of Pink", y:"2003", g:"Experimental / Folktronica"},
      {a:"Arthur Russell", t:"World of Echo", y:"1986", g:"Experimental Pop / Minimalism"},
      {a:"Julianna Barwick", t:"The Magic Place", y:"2011", g:"Ambient / Vocal"},
      {a:"Mary Lattimore", t:"Hundreds of Days", y:"2018", g:"Ambient / Experimental Folk"},
      {a:"Balmorhea", t:"All Is Wild, All Is Silent", y:"2009", g:"Post-Classical / Ambient"},
      {a:"Eluvium", t:"Copia", y:"2007", g:"Ambient / Modern Classical"},
      {a:"Bing & Ruth", t:"No Home of the Mind", y:"2017", g:"Minimalism / Ambient"},
      {a:"Blue Lake", t:"Sun Arcs", y:"2023", g:"Ambient / Experimental"},
      {a:"Arooj Aftab", t:"Vulture Prince", y:"2021", g:"Experimental / Jazz / World"},
      {a:"The Clientele", t:"Suburban Light", y:"2000", g:"Dream Pop / Indie Pop"},
      {a:"Dean Blunt", t:"Black Metal", y:"2014", g:"Experimental R&B / Electronic"},
      {a:"Yves Tumor", t:"Heaven to a Tortured Mind", y:"2020", g:"Art Rock / Alternative R&B"},
      {a:"Tirzah", t:"Devotion", y:"2018", g:"Alternative R&B / Electronic"},
      {a:"Sudan Archives", t:"Athena", y:"2019", g:"Alternative R&B / Experimental Pop"},
      {a:"serpentwithfeet", t:"soil", y:"2018", g:"Alternative R&B / Art Pop"},
      {a:"Shamir", t:"Homo Anxietatem", y:"2022", g:"Art Pop / Indie Rock"},
      {a:"L'Rain", t:"Fatigue", y:"2021", g:"Experimental R&B / Ambient"},
      {a:"Nourished by Time", t:"Catching Chickens", y:"2025", g:"Alternative R&B / Art Pop"},
      {a:"Jessica Pratt", t:"Quiet Signs", y:"2019", g:"Psychedelic Folk / Indie"}
    ]
  }
];
